default: &default
  encoding: utf8
  pool: 30
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>
  host: localhost
  schema_search_path: public

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: d30onc9mfen9lm
  username: mzcpelqikmkkkc
  password: 117bb17501ead3311cc6cf7bc3c35bf82592430ee5f1eb60256a9f1c7789fd34
